[package]
name = "sage-tests"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Unified integration test target for Sage"

[dependencies]
anyhow = { workspace = true }
sage = { workspace = true }
sage-core = { workspace = true }
sage-db = { workspace = true }
sage-archive = { workspace = true }
sage-solver = { workspace = true }
sage-sys = { workspace = true }
sage-build = { workspace = true }
sage-repo = { workspace = true }
bincode = { workspace = true }
heed = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
zstd = { workspace = true }
walkdir = { workspace = true }

[[bin]]
name = "sage-torture"
path = "src/main.rs"
